version '3.9'
services
mysql
image mysql8.0
container_name mysql-db
environment
MYSQL_ROOT_PASSWORD root
MYSQL_DATABASE banco-bootcamp
ports
- 33063306
volumes
- .banco.sqldocker-entrypoint-initdb.dbanco.sql


api
build .api
container_name spring-api
ports
- 80808080
depends_on
- mysql